[ISEEC-972] Add "date" type to data driven componen
boomerang-io/carbon-addons-boomerang-react pull request #9
Opened 2020-12-16 14:18 UTC by LucasGrimauth

## Context

Jira Issue: ISEEC-972

## Checklist:

- [ ] Has been verified in an integrated environment
- [ ] Has relevant unit and integration tests passing
- [ ] Has no linting, test console, or browser console errors (best effort)
- [ ] Has JSDoc comment blocks for complex code

2020-12-16 17:39 UTC, Okisa reviewed
Nice work Lucas!
I was testing the DateInput stories, and at the "with tooltip, label and helper text", there is no no helperText implemented at all. Maybe this is something you can add to improve the component. Overall, everything works fine!

2020-12-16 17:44 UTC, Okisa reviewed
Other thing you can add is a `dateProps` on `determineTypeProps` on `DynamicFormik` to handle any situation that we may need to modify properties for DateInputs there.

2020-12-16 18:09 UTC, LucasGrimauth commented
> Other thing you can add is a `dateProps` on `determineTypeProps` on `DynamicFormik` to handle any situation that we may need to modify properties for DateInputs there.

Yeah, Tim and I discussed about changing the data model. I am thinking the date format pattern (e.g. "Y-m-d") for example would come from the service, not being set directly in the DynamicFormik in the client side. But I will add the `dateProps` as all other inputs have one and is important if we want to do something with the dates input it specifically.

2020-12-17 00:19 UTC, timrbula requested changes
Looking good so far just have a few things left to consider I think.

2020-12-17 00:19 UTC, timrbula commented on src/components/DynamicFormik/DynamicFormik.stories.js
> +    min: '2020-01-01',
`min` and `max` aren't values that are currently coming from our DataDrivenComponent model in the service. I think we need to get the service team to update to include these fields. Min and max could also work for other inputs, like the number input that are currently using `minValueLength` so we should look into that if you haven't.

2020-12-17 00:19 UTC, timrbula commented on src/components/DynamicFormik/DynamicFormik.js
>  import {
I'm not seeing in this file now where its being added to the DynamicFormik validation starting on line 80 in the function `generateYupAst`. It should be added in here and we should look at the different validations we can do that make sense for a date input field

2020-12-31 21:20 UTC, timrbula reviewed
@LucasGrimauth Before merging this in and including it in a new version of the library, we need to make sure that the data model for the services has been updated along w/ the data to use `min` instead of `minValueLength`. We should also check to make sure that any places where we are using the DataDrivenInput directly instead via DynamicFormik are updated to match (I think I did end up doing that in Flow for the Task Upgrade Modal but I am not positive).

 Other than that things are looking good!

2020-12-31 21:20 UTC, timrbula approved these changes, later dismissed

2021-01-07 13:24 UTC, Okisa submitted a review, later dismissed
All seems good and working! 🎉

2021-01-15 16:48 UTC, BenjaminRuby approved these changes
This looks good to me @LucasGrimauth - appreciate the effort on this and thanks for being patient with me as I get up to speed with this component!

2021-01-15 16:48 UTC, merged