fix [ISEEC-4594] Multi select option that contains ":" is shown with no value in the drop down
boomerang-io/carbon-addons-boomerang-react pull request #97
Opened 2023-01-10 16:12 UTC by LucasGrimauth

# PR Template  

Thanks for opening a PR!

## Context

Jira Issue: ISEEC-4594

Version: 3.2.2-beta.0

## PR Review Guidance
Check if you can't add values in Creatable pair that have colons ":"

2023-01-11 17:56 UTC, Okisa reviewed
Looking good in admin!

2023-01-11 17:56 UTC, Okisa commented on src/components/Creatable/Creatable.tsx
> +  const isAddButtonDisabled = disabled || !existValue || invalid || isKeyInputValid || isValueInputValid;
You can remove the || invalid on `isAddButtonDisabled` since this check is already present on `isKeyInputValid` and `isValueInputValid`.

2023-01-13 15:51 UTC, Okisa approved these changes

2023-01-13 16:04 UTC, Okisa requested changes
Hey Lucas! Tested the sing
![CREATABLE_TEST](https://user-images.githubusercontent.com/26601959/212365048-42408ecb-e0bc-4f1d-9d6a-60117702ebc5.gif)
le Creatable, now the Add button is disabled with valid values

2023-01-13 18:05 UTC, LucasGrimauth commented
> Hey Lucas! Tested the single Creatable, now the Add button is disabled with valid values !
@BenjaminRuby @timrbula @Okisa I noticed before my implementation that the Add button would only be disabled if it was passed "disabled" as a prop or if "!existValue". So I added the "invalid" as well to the "isAddButtonDisabled" to disallow wrong values.
But looking at Isa's case in the form, it doesn't work well. So I will change "isAddButtonDisabled" back and just not allow colons.

2023-01-13 21:27 UTC, BenjaminRuby approved these changes, later dismissed
@LucasGrimauth good point on the unexpected behavior with `invalid`

I think we want to create a bug to take a closer look at that and then also the issue that @Okisa brought up with regex issues.

Approving this for now as it should fix the colon issue and won't change anything else

2023-01-13 22:28 UTC, timrbula commented
@LucasGrimauth @BenjaminRuby Just updated types a bit but it is looking good to me

2023-01-13 22:28 UTC, timrbula approved these changes

2023-01-13 22:28 UTC, merged